Add support for classes to isometric objects.
elchininet/isometric pull request #217
Opened 2024-12-20 15:19 UTC by joelburget

Fixes #216

2024-12-20 19:46 UTC, elchininet commented
Hi @joelburget,
Thanks for contributing 🙂
Some things that I have observed in a quick look, please, fix them and I'll review the code with more attention:

1. The `className` should not have an empty string as a default value, this parameter should be added only if it has a value. The snapshots that are not using that option should not have an empty `class` parameter.
2. There should be tests cases for this new option
3. This new option should be added to the documentation to each class
 
Regards and thanks again for contributing to the project.

2024-12-21 00:36 UTC, joelburget commented
I think I fulfilled all of your requests, please let me know how it looks.

2024-12-21 15:51 UTC, elchininet commented
> I think I fulfilled all of your requests, please let me know how it looks.

@joelburget, looks good at first sight. I'll take a deeper look when I have some time. 👍

2024-12-21 23:24 UTC, elchininet requested changes
LGTM, just some removals are required.

2024-12-21 23:24 UTC, elchininet commented on package-lock.json
> +{
Remove this one

2024-12-21 23:24 UTC, elchininet commented on src/@types/type-modules/svg.ts
> +export type SVGProperties = 'fillColor' | 'fillOpacity' | 'strokeColor' | 'strokeOpacity' | 'strokeWidth' | 'className';
The name of the type is confusing. The `className` property should not be here. This type is used only for properties that are animatable.

2024-12-21 23:24 UTC, elchininet commented on src/@utils/svg.ts
> +        'className'
The name of this method is also confusing. Remove the `className` property from here, this is only used to check properties that can be animated.

2024-12-21 23:24 UTC, elchininet commented on src/@utils/svg.ts
> +        className: 'class'
The same with this one, it is used only for animatable properties.

2024-12-21 23:51 UTC, joelburget commented on package-lock.json
> +{
Whoops didn't realize I added this

2024-12-21 23:56 UTC, elchininet commented
@joelburget,
It is ready to merge, rebase with master and solve the conflicts with `dist/web/isometric.js`.

2024-12-22 00:03 UTC, elchininet approved these changes

2024-12-22 00:03 UTC, joelburget commented
I just merged and rebuilt `dist/web/isometric.js` (`git p --no-rebase upstream master; npm run build; git add dist/web/isometric.js`)

2024-12-22 00:13 UTC, merged